### ISSUE TITLE
Projeto 004 - Desenvolvimento da Landing Page e Ambiente de Interação da OID23

### ISSUE THREAD

**Issue by cosmotecnicaAP** [Mutirao/OID23#3]
A Oficina de Inclusão Digital e Participação Social é um evento que reúne atores da sociedade civil, iniciativa privada e órgãos governamentais, tendo como principais objetivos:
                                                                                                                                                      
- Sistematizar o cenário de inclusão digital no país;
- Apontar modelos e métodos de construção de projetos e programas de inclusão digital para governos e sociedade civil;
- Buscar diretrizes para políticas de inclusão de populações vulnerabilizadas e em situação de exclusão, combatendo injustiças sociais geradas pela falta de infraestrutura e pelas assimetrias do acesso. Sempre partindo de uma premissa inicial: a exclusão digital amplia a exclusão social.

DATA: 17, 18 e 19 de outubro de 2023.
LOCAL DO EVENTO: Parque Tecnológico Biotic em Brasília – DF.

Entregas

- [x] #7 @elpadrejorge 
- [x] #8 @elpadrejorge 
- [x] #9 @elpadrejorge 
- [x] #10 @lpirola 
- [x] #11 @lpirola 

Contratação

- [x] Verificar forma de contrato e pagamento
- [x] Emissão de NF (verificar CNPJ para emissão)

**Comment by thaisbtoscano** [comment]
Entregue em 05/10, realizado o repasse do usário para Silvana da Comunicação.

**Comment by thaisbtoscano** [comment]
@uira trouxe a previsão de pagamento para 15 dias após o evento.
