### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by thaisbtoscano** [Mutirao/OID23#7]
Criação de Site da Oficina de Inclusão Digital

MVP
- [x] Página com Logo, Data e Texto curto.
- [x] Demais conteúdos
- [x] Histórico https://oid.org.br/historico/

https://oid.org.br/

**Comment by lpirola** [comment]
Achei esse tema como referência, não sei se temos outras https://wordpress.org/themes/event-star/

**Comment by elpadrejorge** [comment]
Todo o conteúdo da landing page foi atualizado e validado pela Silvana e Wiken. Falta apenas a inserção do feed do Instagram na home, prevista para 03/10.
