### ISSUE TITLE
Sistema de Inscrições

### ISSUE THREAD

**Issue by thaisbtoscano** [Mutirao/OID23#8]
Formulário disponibilizado na Landing Page do Site, contendo:

Nome completo:
Nome para crachá:
Data de nascimento:
Gênero:
CPF:
Instituição:
Email:
Cidade/Estado:
Telefone: 
Bolsa-auxílio: 
Hospedagem:
Deslocamento:
Data da ida:
Trecho ida:
Data da volta:
Trecho volta:

- [ ] Construção
- [ ] Validação
- [ ] Lançamento

Link: https://oid.org.br/pagina-de-inscricao/

**Comment by elpadrejorge** [comment]
Foi acordado com Silvana e Wilken, coordenadores do projeto, que a inscrição seria dividida em dois formulários : Inscrição Simplificada e Inscrição para Bolsa Auxílio.

**Comment by elpadrejorge** [comment]
Entregue em 02/10.
